import type { Metadata } from "next";
import "./globals.css";
import dynamic from "next/dynamic";
import { Cuprum } from "next/font/google";

const cuprum = Cuprum({
  weight: "400",
  subsets: ["latin"],
});

const ClientProvider = dynamic(() => import("./ClientProvider"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Baby Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cuprum.className}>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
